"use client";

import { useState } from "react";
import Stepper from "@/components/Stepper";
import ExternalForm from "@/components/ExternalForm";
import InternalForm from "@/components/InternalForm";
import { promptFor } from "@/lib/prompts";
import { generateDocx } from "@/lib/generate";
import { INTERNAL_FORM_URL } from "@/lib/constants";
import {
  blankResume,
  describeFieldPath,
  findNAIssues,
  formatYearsExperience,
  schemaFor,
  type ExternalResume,
  type InternalResume,
  type ResumeData,
  type TemplateId,
} from "@/lib/schemas";

// Each route is locked to one template's workflow.
export type Audience = TemplateId; // "internal" | "external"

interface FieldError {
  path: string;
  message: string;
}

/** Per-template copy for the "get started" experience (the two choice cards,
 *  the extraction-prompt steps and the paste-JSON hint). */
const START: Record<
  TemplateId,
  {
    boxA: { title: string; body: string; cta: string };
    boxB: { title: string; body: string; cta: string };
    promptSteps: string[];
    pasteSubtext: string;
  }
> = {
  external: {
    boxA: {
      title: "Generate from Candidate Resume",
      body: "Upload the candidate's resume to generate a standardized InfoBeans profile ready for client submission.",
      cta: "Upload resume",
    },
    boxB: {
      title: "Create a Profile from Scratch",
      body: "Start with a blank external profile template and fill in the required details to generate a profile in the InfoBeans standard format.",
      cta: "Get started",
    },
    promptSteps: [
      "Click “Copy LLM Prompt,” then paste the prompt into Gemini together with the candidate's profile PDF.",
      "Once Gemini generates the JSON, copy the entire response.",
      "Click “I Have the JSON”, paste the JSON, and click “Continue”.",
    ],
    pasteSubtext: "Paste the JSON generated by Gemini for the External Profile template, then click “Continue”.",
  },
  internal: {
    boxA: {
      title: "Update an Existing Profile",
      body: "Already have an InfoBeans profile? Upload your latest version to update your information and generate a refreshed profile in standard format.",
      cta: "Upload existing profile",
    },
    boxB: {
      title: "Create a Profile from Scratch",
      body: "Creating your profile for the first time? Start with a blank template and build your InfoBeans profile section by section.",
      cta: "Get started",
    },
    promptSteps: [
      "Click “Copy LLM Prompt” and paste it into Gemini, along with your existing profile PDF.",
      "Once Gemini generates the JSON, copy the entire response.",
      "Click “I Have the JSON”, paste the JSON, and click “Continue”.",
    ],
    pasteSubtext: "Paste the JSON generated by Gemini for the Internal Profile template, then click “Continue”.",
  },
};

const HERO_SUBTEXT: Record<TemplateId, string> = {
  external:
    "Generate a professionally formatted candidate profile in the standard InfoBeans format, ready for client submissions.",
  internal:
    "Your profile is a key branding tool that enables us to showcase your expertise to prospective clients and identify opportunities for role enrichment within the organization.",
};

const STEP_LABELS: Record<TemplateId, string[]> = {
  external: ["Start", "Provide data", "Review & Generate"],
  internal: ["Start", "Provide data", "Review & Generate", "Submit"],
};

export default function ProfileWorkflow({ audience }: { audience: Audience }) {
  const templateId = audience; // the route fixes the template
  const start = START[templateId];

  const [step, setStep] = useState(0);
  // Step 0 has two views: the choice cards and the extraction-prompt screen.
  const [showPromptScreen, setShowPromptScreen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [jsonText, setJsonText] = useState("");
  const [errors, setErrors] = useState<FieldError[] | null>(null);
  const [data, setData] = useState<ResumeData | null>(null);
  // The blank-form route captures the internal experience summary as a bare number of years;
  // the LLM/JSON route supplies the full "<N>+ Years of Industry Experience" string.
  const [fromScratch, setFromScratch] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [generated, setGenerated] = useState<string | null>(null);

  const copyPrompt = async () => {
    await navigator.clipboard.writeText(promptFor(templateId));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const validateJson = (text: string): boolean => {
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch (e) {
      setErrors([{ path: "(document)", message: `Not valid JSON: ${e instanceof Error ? e.message : String(e)}` }]);
      return false;
    }
    const result = schemaFor(templateId).safeParse(parsed);
    if (!result.success) {
      setErrors(
        result.error.issues.map((issue) => ({
          path: issue.path.length ? describeFieldPath(issue.path as (string | number)[]) : "(root)",
          message: issue.message,
        })),
      );
      return false;
    }
    setErrors(null);
    setData(result.data);
    return true;
  };

  const handleJsonChange = (text: string) => {
    setJsonText(text);
    if (errors) setErrors(null);
  };

  const continueToReview = () => {
    if (validateJson(jsonText)) {
      setFromScratch(false); // JSON already carries the full experience-summary string
      setStep(2);
    }
  };

  const startBlankForm = () => {
    setData(blankResume(templateId));
    setFromScratch(true);
    setErrors(null);
    setJsonText("");
    goTo(2);
  };

  const handleGenerate = async () => {
    if (!data) return;

    // In the internal blank-form route the experience summary is captured as a bare number
    // of years; expand it to the full "<N>+ Years of Industry Experience" string used in the
    // document (the LLM/JSON route already supplies that string, so it is left untouched).
    const effective: ResumeData =
      fromScratch && templateId === "internal"
        ? { ...(data as InternalResume), experienceSummary: formatYearsExperience((data as InternalResume).experienceSummary) }
        : data;

    // Re-validate right before generating — covers both the pasted-JSON path and the
    // blank-form path (never validated until now), plus any edits made in the review step
    // since. The "N/A" check only runs here (not on the JSON "Continue" step) so the user
    // can still reach the editable form to fix values the LLM couldn't extract.
    const result = schemaFor(templateId).safeParse(effective);
    if (!result.success) {
      setErrors(
        result.error.issues.map((issue) => ({
          path: issue.path.length ? describeFieldPath(issue.path as (string | number)[]) : "(root)",
          message: issue.message,
        })),
      );
      setGenerateError(null);
      setGenerated(null);
      return;
    }
    const naIssues = findNAIssues(templateId, result.data);
    if (naIssues.length > 0) {
      setErrors(naIssues);
      setGenerateError(null);
      setGenerated(null);
      return;
    }
    setErrors(null);

    setGenerating(true);
    setGenerateError(null);
    setGenerated(null);
    try {
      const candidate = (data as { name?: string }).name?.trim().replace(/\s+/g, "_") || "resume";
      await generateDocx(templateId, result.data, `${candidate}_${templateId}_profile.docx`);
      setGenerated("DOCX downloaded — check your downloads.");
    } catch (e) {
      setGenerateError(e instanceof Error ? e.message : String(e));
    } finally {
      setGenerating(false);
    }
  };

  const goTo = (target: number) => {
    setStep(target);
    setGenerateError(null);
    setGenerated(null);
    setErrors(null);
  };

  return (
    <div className="w-full text-ink">
      {/* hero — same heading for both routes, subtext is per-audience */}
      <section className="bg-cream">
        <div className="mx-auto max-w-6xl px-4 py-12 text-center">
          <h1 className="text-3xl font-bold tracking-tight text-ink-dark sm:text-4xl">InfoBeans Profile Generator</h1>
          <p className="mx-auto mt-3 max-w-xl text-sm text-ink-light sm:text-base">{HERO_SUBTEXT[templateId]}</p>
        </div>
      </section>

      <main className="mx-auto max-w-6xl px-4 py-10">
        <div className="mb-10">
          <Stepper current={step} onNavigate={goTo} labels={STEP_LABELS[templateId]} />
        </div>

        {/* ---------- STEP 0: start experience ---------- */}
        {step === 0 && (
          <div className="animate-fade-up space-y-6">
            {!showPromptScreen ? (
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="flex flex-col rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <h3 className="mb-2 font-semibold text-ink-dark">{start.boxA.title}</h3>
                  <p className="mb-5 flex-1 text-sm text-ink-light">{start.boxA.body}</p>
                  <button
                    type="button"
                    onClick={() => setShowPromptScreen(true)}
                    className="self-start rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600"
                  >
                    {start.boxA.cta}
                  </button>
                </div>
                <div className="flex flex-col rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <h3 className="mb-2 font-semibold text-ink-dark">{start.boxB.title}</h3>
                  <p className="mb-5 flex-1 text-sm text-ink-light">{start.boxB.body}</p>
                  <button
                    type="button"
                    onClick={startBlankForm}
                    className="self-start rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600"
                  >
                    {start.boxB.cta}
                  </button>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <h3 className="mb-3 font-semibold text-ink-dark">Get the extraction prompt</h3>
                  <ol className="mb-4 list-decimal space-y-2 pl-5 text-sm text-ink-light">
                    {start.promptSteps.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ol>
                  <div className="flex items-center gap-3">
                    <button
                      type="button"
                      onClick={copyPrompt}
                      className="rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600"
                    >
                      {copied ? "Copied ✓" : "Copy LLM Prompt"}
                    </button>
                    <button
                      type="button"
                      onClick={() => goTo(1)}
                      className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
                    >
                      I Have the JSON →
                    </button>
                  </div>
                  <details className="mt-4">
                    <summary className="cursor-pointer text-xs text-ink-light hover:text-ink">Preview prompt</summary>
                    <pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded-md bg-ink-dark p-3 text-xs text-gray-100">
                      {promptFor(templateId)}
                    </pre>
                  </details>
                </div>
                <button
                  type="button"
                  onClick={() => setShowPromptScreen(false)}
                  className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
                >
                  ← Back
                </button>
              </div>
            )}
          </div>
        )}

        {/* ---------- STEP 1: paste JSON ---------- */}
        {step === 1 && (
          <div className="animate-fade-up space-y-4">
            <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
              <h2 className="mb-2 font-semibold text-ink-dark">Paste the JSON</h2>
              <p className="mb-3 text-sm text-ink-light">{start.pasteSubtext}</p>
              <textarea
                value={jsonText}
                onChange={(e) => handleJsonChange(e.target.value)}
                spellCheck={false}
                rows={16}
                placeholder='{"name": "…", "jobTitle": "…", …}'
                className="w-full rounded-md border border-gray-300 p-3 font-mono text-xs text-ink focus:border-brand-500 focus:outline-none focus:ring-1 focus:ring-brand-500"
              />
              {errors && (
                <div className="mt-3 rounded-md border border-brand-200 bg-brand-50 p-3">
                  <p className="mb-2 text-sm font-semibold text-brand-700">
                    {errors.length} validation {errors.length === 1 ? "issue" : "issues"}:
                  </p>
                  <ul className="space-y-1 text-sm text-brand-700">
                    {errors.map((err, i) => (
                      <li key={i}>
                        <code className="rounded bg-brand-100 px-1 py-0.5 text-xs">{err.path}</code> — {err.message}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
            <div className="flex justify-between">
              <button
                type="button"
                onClick={() => {
                  setShowPromptScreen(true);
                  goTo(0);
                }}
                className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
              >
                ← Back
              </button>
              <button
                type="button"
                onClick={continueToReview}
                disabled={!jsonText.trim()}
                className="rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600 disabled:opacity-40"
              >
                Continue →
              </button>
            </div>
          </div>
        )}

        {/* ---------- STEP 2: review & generate ---------- */}
        {step === 2 && data && (
          <div className="animate-fade-up space-y-5">
            {templateId === "external" ? (
              <ExternalForm
                data={data as ExternalResume}
                onChange={(d) => {
                  setData(d);
                  if (errors) setErrors(null);
                }}
              />
            ) : (
              <InternalForm
                data={data as InternalResume}
                fromScratch={fromScratch}
                onChange={(d) => {
                  setData(d);
                  if (errors) setErrors(null);
                }}
              />
            )}

            {errors && (
              <div className="rounded-md border border-brand-200 bg-brand-50 p-3">
                <p className="mb-2 text-sm font-semibold text-brand-700">
                  Can&apos;t generate yet — {errors.length} {errors.length === 1 ? "issue" : "issues"} to fix:
                </p>
                <ul className="space-y-1 text-sm text-brand-700">
                  {errors.map((err, i) => (
                    <li key={i}>
                      <code className="rounded bg-brand-100 px-1 py-0.5 text-xs">{err.path}</code> — {err.message}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {generateError && (
              <div className="whitespace-pre-wrap rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">
                {generateError}
              </div>
            )}
            {generated && !generateError && (
              <div className="rounded-md border border-green-200 bg-green-50 p-3 text-sm text-green-700">{generated}</div>
            )}

            <div className="flex flex-wrap items-center justify-between gap-3">
              <button
                type="button"
                onClick={() => goTo(1)}
                className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
              >
                ← Back
              </button>
              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={handleGenerate}
                  disabled={generating}
                  className="rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600 disabled:opacity-50"
                >
                  {generating ? "Generating…" : "DOCX ↓"}
                </button>
                {templateId === "internal" && generated && !generateError && (
                  <button
                    type="button"
                    onClick={() => goTo(3)}
                    className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
                  >
                    Continue to Submit →
                  </button>
                )}
              </div>
            </div>
          </div>
        )}

        {/* ---------- STEP 3: submit (internal only) ---------- */}
        {step === 3 && templateId === "internal" && (
          <div className="animate-fade-up space-y-4">
            <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
              <h2 className="mb-2 font-semibold text-ink-dark">Submit your profile</h2>
              <p className="mb-4 text-sm text-ink-light">
                Once you&apos;ve downloaded your profile, upload the generated DOCX file through the Google Form
                below to complete your profile submission.
              </p>
              <a
                href={INTERNAL_FORM_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-block rounded-md bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600"
              >
                Open submission form →
              </a>
            </div>
            <button
              type="button"
              onClick={() => goTo(2)}
              className="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-ink hover:bg-gray-50"
            >
              ← Back
            </button>
          </div>
        )}
      </main>
    </div>
  );
}
