/**
 * Purpose: tests for resume text extraction — sidebar/main column separation and skill-rating
 * pairing across a page break, using PDFs generated by lib/pdf.ts. Run with `npm test`.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildResumePdf, type PdfAssets } from "./pdf";
import { extractResumeText, splitColumns, type PdfTextItem } from "./extractText";
import type { ExternalResume, InternalResume } from "./schemas";

const assets: PdfAssets = {
  lexendLight: fs.readFileSync("public/fonts/LexendLight-regular.ttf"),
  lexend: fs.readFileSync("public/fonts/Lexend-regular.ttf"),
  lexendMedium: fs.readFileSync("public/fonts/LexendMedium-regular.ttf"),
  logoPng: fs.readFileSync("public/img/logo.png"),
};

const overview = "Engineer with broad platform experience across many projects and domains. ".repeat(4);

const internal = (skillCount: number): InternalResume => ({
  name: "Test Person",
  jobTitle: "Lead Engineer",
  experienceSummary: "8+ Years of Industry Experience",
  specialization: "Cloud Platforms",
  overview,
  education: [{ year: "2012", qualification: "B.E. (IT), RGPV Bhopal" }],
  projects: Array.from({ length: 3 }, (_, i) => ({
    duration: "Jan 2022 - Dec 2022",
    title: `Project ${i}`,
    toolsAndTechnologies: ["Go", "Postgres"],
    teamSize: "7-8",
    role: "Tech Lead",
    projectLink: "NDA",
    description: overview,
    responsibilities: ["Led the design.", "Shipped version one."],
  })),
  skills: Array.from({ length: skillCount }, (_, i) => ({ name: `Skill${String(i).padStart(2, "0")}`, rating: `${(i % 4) + 1}.5` })),
  certifications: ["AWS SA Pro"],
  tools: ["JIRA", "GIT"],
  managerialExperience: ["Project Management"],
  domains: ["Fintech"],
  languages: ["English"],
});

test("sidebar skills stay paired with their ratings, even across a page break", async () => {
  const pdf = await buildResumePdf("internal", internal(70), assets);
  const { text } = await extractResumeText(Buffer.from(pdf));
  const [main, sidebar] = text.split("--- SIDEBAR ---");
  assert.ok(sidebar, "expected a sidebar section");
  assert.ok(main.includes("Project 2"), "main column should hold the projects");
  assert.ok(!main.includes("Skill00"), "skills must not be mixed into the main column");
  const lines = sidebar.split("\n").map((l) => l.trim());
  for (let i = 0; i < 70; i++) {
    const idx = lines.indexOf(`Skill${String(i).padStart(2, "0")}`);
    assert.notEqual(idx, -1, `Skill${i} missing from sidebar`);
    assert.equal(lines[idx + 1], `(${(i % 4) + 1}.5/5)`, `Skill${i} is not followed by its rating`);
  }
});

test("single-column external profile has no sidebar section", async () => {
  const external: ExternalResume = {
    name: "Test Person",
    jobTitle: "Lead Engineer",
    experienceSummary: "8+ Years of Industry Experience",
    specialization: "Cloud Platforms",
    overview,
    education: [{ year: "2012", qualification: "B.E. (IT), RGPV Bhopal" }],
    skills: ["AWS", "Go"],
    tools: ["JIRA"],
    certifications: ["CKA"],
    projects: [],
    experience: [{ company: "Acme", position: "Engineer", duration: "2015 - 2020", highlights: [overview, overview] }],
  };
  const { text } = await extractResumeText(Buffer.from(await buildResumePdf("external", external, assets)));
  assert.ok(!text.includes("--- SIDEBAR ---"));
  assert.ok(text.includes("2012"), "short numeric lines such as years must be kept");
});

test("splitColumns: single column of wide words is not split", () => {
  const items: PdfTextItem[] = Array.from({ length: 40 }, (_, i) => ({ str: "word", x: 72 + (i % 10) * 45, y: 700 - i * 3, width: 40 }));
  assert.equal(splitColumns(items, 612).sidebar.length, 0);
});
