/**
 * Purpose: tests for resume text extraction — sidebar/main column separation and skill-rating
 * pairing across a page break, using PDFs generated by lib/pdf.ts. Run with `npm test`.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildResumePdf, type PdfAssets } from "./pdf";
import { PDFDocument, StandardFonts } from "pdf-lib";
import { extractResumeText, removeHeaderFooterItems, splitColumns, stripRepeatedLines, type PdfTextItem } from "./extractText";
import type { ExternalResume, InternalResume } from "./schemas";

const assets: PdfAssets = {
  lexendLight: fs.readFileSync("public/fonts/LexendLight-regular.ttf"),
  lexend: fs.readFileSync("public/fonts/Lexend-regular.ttf"),
  lexendMedium: fs.readFileSync("public/fonts/LexendMedium-regular.ttf"),
  logoPng: fs.readFileSync("public/img/logo.png"),
};

const overview = "Engineer with broad platform experience across many projects and domains. ".repeat(4);

const internal = (skillCount: number): InternalResume => ({
  name: "Test Person",
  jobTitle: "Lead Engineer",
  experienceSummary: "8+ Years of Industry Experience",
  specialization: "Cloud Platforms",
  overview,
  education: [{ year: "2012", qualification: "B.E. (IT), Riverside University" }],
  projects: Array.from({ length: 3 }, (_, i) => ({
    duration: "Jan 2022 - Dec 2022",
    title: `Project ${i}`,
    toolsAndTechnologies: ["Go", "Postgres"],
    teamSize: "7-8",
    role: "Tech Lead",
    projectLink: "NDA",
    description: overview,
    responsibilities: ["Led the design.", "Shipped version one."],
  })),
  skills: Array.from({ length: skillCount }, (_, i) => ({ name: `Skill${String(i).padStart(2, "0")}`, rating: `${(i % 4) + 1}.5` })),
  certifications: ["AWS SA Pro"],
  tools: ["JIRA", "GIT"],
  managerialExperience: ["Project Management"],
  domains: ["Fintech"],
  languages: ["English"],
});

test("sidebar skills stay paired with their ratings, even across a page break", async () => {
  const pdf = await buildResumePdf("internal", internal(70), assets);
  const { text } = await extractResumeText(Buffer.from(pdf));
  const [main, sidebar] = text.split("--- SIDEBAR ---");
  assert.ok(sidebar, "expected a sidebar section");
  assert.ok(main.includes("Project 2"), "main column should hold the projects");
  assert.ok(!main.includes("Skill00"), "skills must not be mixed into the main column");
  const lines = sidebar.split("\n").map((l) => l.trim());
  for (let i = 0; i < 70; i++) {
    const idx = lines.indexOf(`Skill${String(i).padStart(2, "0")}`);
    assert.notEqual(idx, -1, `Skill${i} missing from sidebar`);
    assert.equal(lines[idx + 1], `(${(i % 4) + 1}.5/5)`, `Skill${i} is not followed by its rating`);
  }
});

test("single-column external profile has no sidebar section", async () => {
  const external: ExternalResume = {
    name: "Test Person",
    jobTitle: "Lead Engineer",
    experienceSummary: "8+ Years of Industry Experience",
    specialization: "Cloud Platforms",
    overview,
    education: [{ year: "2012", qualification: "B.E. (IT), Riverside University" }],
    skills: ["AWS", "Go"],
    tools: ["JIRA"],
    certifications: ["CKA"],
    projects: [],
    experience: [{ company: "Acme", position: "Engineer", duration: "2015 - 2020", highlights: [overview, overview] }],
  };
  const { text } = await extractResumeText(Buffer.from(await buildResumePdf("external", external, assets)));
  assert.ok(!text.includes("--- SIDEBAR ---"));
  assert.ok(text.includes("2012"), "short numeric lines such as years must be kept");
});

test("splitColumns: single column of wide words is not split", () => {
  const items: PdfTextItem[] = Array.from({ length: 40 }, (_, i) => ({ str: "word", x: 72 + (i % 10) * 45, y: 700 - i * 3, width: 40 }));
  assert.equal(splitColumns(items, 612).sidebar.length, 0);
});

test("stripRepeatedLines: a lone number starting a page is kept; a numbered footer run is dropped", () => {
  const kept = stripRepeatedLines(["Project\nTeam Size", "3\nRole"]);
  assert.ok(kept[1].startsWith("3"), "team size at the top of a page must survive");
  const dropped = stripRepeatedLines(["Intro text\n1", "More text\n2", "Last text\n3"]);
  assert.deepEqual(dropped.map((p) => p.trim()), ["Intro text", "More text", "Last text"]);
});

/* ---------- regression: team size range lost on a multi-page InfoBeans profile ---------- */

/** Builds the internal PDF and stamps a bare page number in the footer of every page, like Google Docs does. */
async function withFooterNumbers(resume: InternalResume): Promise<{ bytes: Uint8Array; pages: number }> {
  const doc = await PDFDocument.load(await buildResumePdf("internal", resume, assets));
  const font = await doc.embedFont(StandardFonts.Helvetica);
  doc.getPages().forEach((page, i) => page.drawText(String(i + 1), { x: 511, y: 21, size: 9, font }));
  return { bytes: await doc.save(), pages: doc.getPageCount() };
}

test("field labels repeated on every project survive, ranges stay attached, footer numbers are gone", async () => {
  const base = internal(6);
  const sizes = ["7-8", "4", "5-6", "9", "5-6"];
  const resume: InternalResume = {
    ...base,
    projects: sizes.map((teamSize, i) => ({
      ...base.projects[0],
      title: `Project ${i}`,
      teamSize,
      role: i === 2 ? "Tier 3 Backend Developer" : "Backend Developer",
      description: overview.repeat(2),
    })),
  };
  const { bytes, pages } = await withFooterNumbers(resume);
  assert.ok(pages >= 3, `expected a 3+ page PDF, got ${pages}`);
  const { text } = await extractResumeText(Buffer.from(bytes));
  const lines = text.split("\n").map((l) => l.trim());

  const labelAt = lines.flatMap((l, i) => (l === "Team Size" ? [i] : []));
  assert.equal(labelAt.length, sizes.length, "every project keeps its Team Size label");
  assert.deepEqual(labelAt.map((i) => lines[i + 1]), sizes, "each label is followed by its own value, incl. ranges");
  assert.equal(lines.filter((l) => l === "Role").length, sizes.length, "Role labels survive too");
  for (const n of ["1", "2", "3"]) assert.ok(!lines.includes(n), `footer page number ${n} must not leak into the text`);
});

test("stripRepeatedLines keeps repeated field labels and anything directly after a label", () => {
  const page = (v: string) => `Project\nTeam Size\n${v}\nRole`;
  const out = stripRepeatedLines([page("7-8"), page("2"), page("3")]);
  out.forEach((p) => assert.ok(p.includes("Team Size") && p.includes("Role")));
  assert.ok(out[1].includes("\n2\n"), "a lone number after a label is the value, not a page number");
  // even when the values would otherwise look like a 1,2,3 page-number run at the page start
  const run = stripRepeatedLines(["Team Size\n1", "Team Size\n2", "Team Size\n3"]);
  assert.deepEqual(run, ["Team Size\n1", "Team Size\n2", "Team Size\n3"]);
});

test("a range 'N-M' is never a page number", () => {
  const out = stripRepeatedLines(["intro\n5-6", "5-6\nmore", "x\n7-8"]);
  assert.deepEqual(out, ["intro\n5-6", "5-6\nmore", "x\n7-8"]);
});

test("removeHeaderFooterItems: drops footer numbers and repeated band text, keeps body numbers", () => {
  const body = (str: string, y: number): PdfTextItem => ({ str, x: 51, y, width: 10 });
  const pages = [1, 2, 3].map((n) => [
    body("Team Size", 600),
    body("5-6", 585),
    body("3", 570), // a body value that looks like a page number
    body(String(n), 21), // footer page number
    body("InfoBeans Confidential", 15), // repeated footer
  ]);
  const cleaned = removeHeaderFooterItems(pages, [792, 792, 792]);
  cleaned.forEach((items) => assert.deepEqual(items.map((i) => i.str), ["Team Size", "5-6", "3"]));
});
